# Generated by Django 4.2.23 on 2025-11-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueSettings',
            new_name='LeagueSetting',
        ),
    ]
