# Generated by Django 4.2.23 on 2025-11-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_leaguesettings_leaguesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguesetting',
            name='created_at',
        ),
    ]
