# Generated by Django 4.2.23 on 2025-11-03 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_leaguesetting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.PositiveIntegerField()),
                ('matchup1', models.CharField(blank=True, max_length=100, null=True)),
                ('matchup2', models.CharField(blank=True, max_length=100, null=True)),
                ('matchup3', models.CharField(blank=True, max_length=100, null=True)),
                ('matchup4', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['weekNumber'],
            },
        ),
        migrations.CreateModel(
            name='UserLeagueStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceBought', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='leagueparticipant',
            options={},
        ),
        migrations.RemoveField(
            model_name='leagueparticipant',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='leagueparticipant',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='leagueparticipant',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='leaguesetting',
            name='league_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.AddField(
            model_name='userleaguestocks',
            name='LeagueParticipant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.leagueparticipant'),
        ),
        migrations.AddField(
            model_name='userleaguestocks',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stock'),
        ),
        migrations.AddField(
            model_name='leagueschedule',
            name='League',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='catalog.leaguesetting'),
        ),
        migrations.AlterUniqueTogether(
            name='leagueschedule',
            unique_together={('League', 'weekNumber')},
        ),
    ]
