# Generated by Django 4.2.23 on 2025-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_leagueschedule_userleaguestocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleaguestocks',
            name='shares',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
