# Generated by Django 4.2.23 on 2025-11-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_userleaguestocks_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.PositiveIntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='catalog.leaguesetting')),
            ],
            options={
                'ordering': ['weekNumber'],
            },
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='losses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='wins',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LeagueSchedule',
        ),
        migrations.AddField(
            model_name='matchup',
            name='participant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_p1', to='catalog.leagueparticipant'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='participant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_p2', to='catalog.leagueparticipant'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchup_wins', to='catalog.leagueparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='matchup',
            unique_together={('league', 'weekNumber', 'participant1', 'participant2')},
        ),
    ]
