# Generated by Django 4.2.23 on 2025-11-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_matchup_leagueparticipant_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='profit1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='matchup',
            name='profit2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
