# Generated by Django 4.2.23 on 2025-11-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_matchup_profit1_matchup_profit2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeagueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_start_of_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shares', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('league_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.leagueparticipant')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.stock')),
            ],
        ),
        migrations.RenameModel(
            old_name='LeagueSetting',
            new_name='League',
        ),
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ['week_number']},
        ),
        migrations.RenameField(
            model_name='matchup',
            old_name='profit1',
            new_name='start_of_week_net_worth1',
        ),
        migrations.RenameField(
            model_name='matchup',
            old_name='profit2',
            new_name='start_of_week_net_worth2',
        ),
        migrations.RenameField(
            model_name='matchup',
            old_name='weekNumber',
            new_name='week_number',
        ),
        migrations.AlterUniqueTogether(
            name='matchup',
            unique_together={('league', 'week_number', 'participant1', 'participant2')},
        ),
        migrations.DeleteModel(
            name='UserLeagueStocks',
        ),
    ]
