# Generated by Django 4.2.23 on 2025-11-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_userleaguestock_rename_leaguesetting_league_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='league',
            name='is_active',
        ),
    ]
